### PR TITLE
feat: add toggle feature

### PR DESCRIPTION
**Pull request by TanmayBhosale**
Issue: #16 

Have added the toggle feature. The toggle button is at the top right. I wasn't sure what icons are we using, so haven't added icons. Have a look at the color theme and if it is fine let me know which icons to use, (fontawesome, feather icons, etc) I'll add it

### CODE REVIEW

**Review by Coding-Hashira — COMMENTED** [review]
Everything is awesome! But two things aren't visible in Dark Mode:
1. The GitHub Icon at footer
2. Threadify Logo (You can try applying CSS filters to the image)

Please fix this issue!

**Comment by TanmayBhosale** [comment]
Yup, sure! I'll add a Github icon instead of a SVG. Any suggestions on which icons to use? Fontawesome or anything else?

**Comment by Coding-Hashira** [comment]
> Yup, sure! I'll add a Github icon instead of a SVG. Any suggestions on which icons to use? Fontawesome or anything else?

Can't we just use [react-icons](https://react-icons.github.io/react-icons/)? It has almost every icon we need!

**Comment by TanmayBhosale** [comment]
Yup I just pushed the icon fix will add the icons as well

**Comment by Coding-Hashira** [comment]
Should we also update the Twitter icon? Like change it to white, too?

Everything else seems fine currently!

**Comment by Coding-Hashira** [comment]
And yea, you can use basic sun and moon icons for toggle button.

**Comment by TanmayBhosale** [comment]
Yup will do

**Comment by pushkaraj2007** [comment]
I think it looks good now, thanks for contributing @TanmayBhosale 

Going to merge it.

**Review by pushkaraj2007 — APPROVED** [review]
I think it looks good now, thanks for contributing @TanmayBhosale

Going to merge it.

**Comment by pushkaraj2007** [comment]
Also thanks to @Coding-Hashira, for reviewing PR and suggesting changes.

**Pull request merged**
