### PR TITLE
Layout component

### PR DESCRIPTION
**Pull request by stevenovak123**
This solves issue #20

### CODE REVIEW

**Comment by stevenovak123** [comment]
Hey. If I add this as layout file then the Themes will have to be reworked as themes dont get applied to the Navbar and footer. 
What do you suggest that I should do for this. 
I'm thinking that I need to call the ``useTheme`` hook in Layout and then pass is down

**Comment by TanmayBhosale** [comment]
Can you style Navbar and footer individually? Like apply bg and dark:bg classes to navbar and footer.

**Comment by stevenovak123** [comment]
Could you elaborate more on this? I didnt quiet get it. The Navbar and footer already have individual styles of bg and dark:bg classes in their individual components. Its just that with ``Layout.tsx`` it doesnt work as intended, the ``ThemeProvider`` wraps the layout as well.

**Comment by TanmayBhosale** [comment]
add these classes to navbar.tsx line 14 dark:bg-gray-900 bg-gray-100. Similarly add it to footer. It is working

**Comment by stevenovak123** [comment]
> add these classes to navbar.tsx line 14 `dark:bg-gray-900 bg-gray-100`. Similarly add it to footer. It is working

Yep. Thank you it works.

**Comment by TanmayBhosale** [comment]
Cool!

**Review by pushkaraj2007 — APPROVED** [review]
Looks great 🔥

Thanks for contributing, hope to see you again around the project 🚀

**Pull request merged**
