### PR TITLE
test

### PR DESCRIPTION
**Pull request by KendallDoesCoding**

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
> Someone is attempting to deploy a commit to a Personal Account owned by @pushkaraj2007 on [Vercel](https://vercel.com).
> 
> @pushkaraj2007 first needs to [authorize it](https://vercel.com/git/authorize?type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%22db39b220c065c2d15c90ad105bb71cf4ea279907%22%7D%2C%22id%22%3A%22QmcmjvqGqk6TE7eGKUxXREJnzzTPMYMW6e3Ma5qwziVsgw%22%2C%22org%22%3A%22pushkaraj2007%22%2C%22prId%22%3A51%2C%22repo%22%3A%22Threadify%22%7D).

@pushkaraj2007 - please authorize, I want to see if this works or not.

**Comment by pushkaraj2007** [comment]
Sure @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
Thanks @pushkaraj2007 , I was trying to fix a issue that I found but it didn't work.

See #52

**Comment by pushkaraj2007** [comment]
@KendallDoesCoding 

You made a spelling mistake in the code, it's not 'Thredif' but 'Thredify'

**Pull request closed without merging**
