### PR TITLE
Updated social links in Footer.tsx

### LINKED ISSUE #43: Update of social links to enable opening in new tabs
**Describe the bug**
All the social links at the bottom of the page open in the same tab as the current tab.
Changing this to open in new tab will make its use more comfortable to users as they don't hav to go to previous tab for every social logo .

**To Reproduce**
1. Go to https://threadify.vercel.app/
2. Scroll down to see the social logos( github and twitter)
3. Click on twitter or github logo.
4. See that whatever social logo is clicked that link is opened in the same tab as the current tab

**Expected behavior**
I would like this to be able to open each social link in a new tab for ese of use and access of the threadify after use of social links

**Screenshots**
`See that these links open in the same tab`

image

image

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: OPera
 - Version: LVL4 (core: 95.0.4635.74)

### PR DESCRIPTION
**Pull request by tmsagarofficial**
This PR fixes #43

### CODE REVIEW

**Comment by tmsagarofficial** [comment]
> Someone is attempting to deploy a commit to a Personal Account owned by @pushkaraj2007 on [Vercel](https://vercel.com).
> 
> @pushkaraj2007 first needs to [authorize it](https://vercel.com/git/authorize?type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%22bfbe7fef55bfc9ce713d078c9b8eeae7c5da2dc7%22%7D%2C%22id%22%3A%22QmaA5maxVCZcpxtMfY1EbLhzZfe9UrfmQf9MH3AG2QJJ7T%22%2C%22org%22%3A%22pushkaraj2007%22%2C%22prId%22%3A45%2C%22repo%22%3A%22Threadify%22%7D).

@pushkaraj2007 Pls look into my PR

**Review by pushkaraj2007 — CHANGES_REQUESTED** [review]
Can you please check and fix the errors occurring?
image

**Review by tmsagarofficial — COMMENTED** [review]
I'm done with the required changes.

**Comment by tmsagarofficial** [comment]
check now @pushkaraj2007

**Review by pushkaraj2007 — APPROVED** [review]
Looks good 🔥

Thanks for contributing, don't forget to leave a star if you liked the project ⭐

**Pull request merged**
