### PR TITLE
fix: uniform feature boxes

### PR DESCRIPTION
**Pull request by selemondev**

### CODE REVIEW

**Review by pushkaraj2007 — COMMENTED** [review]
Can you please explain a bit, what this PR does?

**Comment by selemondev** [comment]
Threadify's feature boxes are not uniform. This PR intends to make the feature boxes uniform by giving the same size to all the feature boxes and also to refactor some code to make the code more readable and less verbose.

**Review by pushkaraj2007 — CHANGES_REQUESTED** [review]
Some images in the feature boxes are broken, can you please take a look at them, and if possible can you please fix them?

**Comment by selemondev** [comment]
Sure

**Comment by selemondev** [comment]
Images fixed and merge conflicts resolved !!

**Review by pushkaraj2007 — COMMENTED** [review]
I think it's irrelevant now, so I'm going to close this!!

**Pull request closed without merging**
