### PR TITLE
Add contributors page

### PR DESCRIPTION
**Pull request by TanmayBhosale**
Fix: #23 

Make sure to add the env variables as mentioned [here](https://github.com/pushkaraj2007/Threadify/issues/23#issuecomment-1279704075)

### CODE REVIEW

**Review by pushkaraj2007 — COMMENTED** [review]
Getting some errors while building, can you please fix them?
Screenshot 2022-10-15 225434

**Comment by TanmayBhosale** [comment]
I have made the changes. Can you please check? I think the issue is with credentials. if the credentials are invalid, GitHub still returns a JSON response with a 200 status. I have made the changes to check for the response. Please verify

**Comment by pushkaraj2007** [comment]
Terminal errors have been solved, but when I go to /contributors URL it doesn't list the contributors.

Is this the same happening to you? If so, can you please fix it?

**Comment by TanmayBhosale** [comment]
I think this problem is because of the credentials. Can you regenerate the credentials? Create it from [here](https://github.com/settings/tokens/new) . Set the expiration to no expiration and just select all the repo permissions.

**Comment by pushkaraj2007** [comment]
You mean the first repo permission boxes, right? 

And as you said I have already set the expiration to no expiration.

**Comment by TanmayBhosale** [comment]
okay and have you set your GitHub user to pushkaraj2007?

**Comment by pushkaraj2007** [comment]
Yeah! I did it.

**Comment by TanmayBhosale** [comment]
Okay, I'll look into it.

**Comment by pushkaraj2007** [comment]
Is it working on your local machine?

**Comment by TanmayBhosale** [comment]
yup it is

**Comment by TanmayBhosale** [comment]
Is vercel deploying my changes? I think vercel is not deploying the preview. I have added some logs to locate the problem

**Comment by pushkaraj2007** [comment]
I think it's not, let me see why this is happening...

**Comment by TanmayBhosale** [comment]
yup

**Comment by pushkaraj2007** [comment]
Hey, bro I think I should merge it. 

If we got any other issues we'll fix that with another commits and PRs. 

What do you think?

**Review by pushkaraj2007 — APPROVED** [review]
Looks good 🔥

Thanks for contributing!! 🚀

**Pull request merged**
